// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Modifier } from "./Modifier";

export type ShortcutBinding = { key: string, modifiers: Array<Modifier>, };
