// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ShortcutId = "toggle-sidebar" | "toggle-tab-bar" | "cycle-tab-forward" | "cycle-tab-backward" | "new-note" | "open-settings";
