[package]
name = "notara-mac-window"
links = "notara-mac-window"
version = "0.1.0"
edition = "2021"
publish = false

[build-dependencies]
tauri-plugin = { version = "2", features = ["build"] }

[target.'cfg(target_os = "macos")'.dependencies]
cocoa = "0.26.0"
objc = "0.2.7"
csscolorparser = "0.7.0"
log = "0.4"

[dependencies]
tauri = { version = "2" }
